language: python
python:
  - "3.7"
install:
  - pip install -r test/pip_requirements.txt
  - pip install coverage
  - pip install python-coveralls
  - pip install pytest-cov
script:
  - python -m pytest tests/
after_success: 
